version: "3.8"
services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - pg_data_booking_system:/var/lib/postgresql/data
  adminer_booking_system:
    image: adminer
    container_name: adminer_booking_system
    ports:
      - "8080:8080"
    links:
      - "db:db"
    # networks:
    #   - dbnet
    depends_on:
      - db

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend

volumes:
  pg_data_booking_system: